add_test([=[ShaderUtilsTest.CompileTest]=]  /home/runner/work/vsdf/vsdf/build_san/tests/vsdf_tests [==[--gtest_filter=ShaderUtilsTest.CompileTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShaderUtilsTest.CompileTest]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/vsdf/vsdf/build_san/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShaderUtilsTest.CompileVertexShader]=]  /home/runner/work/vsdf/vsdf/build_san/tests/vsdf_tests [==[--gtest_filter=ShaderUtilsTest.CompileVertexShader]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShaderUtilsTest.CompileVertexShader]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/vsdf/vsdf/build_san/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShaderUtilsTest.CompileGLSLESTest]=]  /home/runner/work/vsdf/vsdf/build_san/tests/vsdf_tests [==[--gtest_filter=ShaderUtilsTest.CompileGLSLESTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShaderUtilsTest.CompileGLSLESTest]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/vsdf/vsdf/build_san/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShaderUtilsTest2.CompileTestBadVersion]=]  /home/runner/work/vsdf/vsdf/build_san/tests/vsdf_tests [==[--gtest_filter=ShaderUtilsTest2.CompileTestBadVersion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShaderUtilsTest2.CompileTestBadVersion]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/vsdf/vsdf/build_san/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  vsdf_tests_TESTS ShaderUtilsTest.CompileTest ShaderUtilsTest.CompileVertexShader ShaderUtilsTest.CompileGLSLESTest ShaderUtilsTest2.CompileTestBadVersion)
